version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: amarsingh3d/apache2.4-php7.2
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 1024M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
#    networks:
#      - webnet
#networks:
#  webnet:
